'use client';
import {useEffect,useRef} from 'react';
import * as T from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {atlas,dimensions,parts,type Region} from '@/lib/skin/atlas';
import {pixelCanvas,type Skin,type View} from '@/lib/skin/engine';
export default function SkinView({skin,view,onPixel,paint=false}:{skin:Skin;view:View;onPixel?:(x:number,y:number)=>void;paint?:boolean}){
 const host=useRef<HTMLDivElement>(null);const callback=useRef(onPixel);callback.current=onPixel;const state=useRef<{texture:T.CanvasTexture;scene:T.Scene;meshes:T.Mesh[];render:()=>void;controls:OrbitControls}|null>(null);
 useEffect(()=>{if(!host.current)return;const el=host.current;const scene=new T.Scene();scene.add(new T.AmbientLight(0xffffff,2.2));const light=new T.DirectionalLight(0xffffff,1.5);light.position.set(-20,50,45);scene.add(light);const camera=new T.PerspectiveCamera(32,1,.1,1000);camera.position.set(43,27,66);const renderer=new T.WebGLRenderer({antialias:true,alpha:true,preserveDrawingBuffer:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=T.SRGBColorSpace;el.appendChild(renderer.domElement);const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(0,15,0);controls.enablePan=false;controls.minDistance=38;controls.maxDistance=260;controls.enableDamping=false;const texture=new T.CanvasTexture(pixelCanvas(skin.pixels));texture.magFilter=T.NearestFilter;texture.minFilter=T.NearestFilter;texture.colorSpace=T.SRGBColorSpace;const meshes:T.Mesh[]=[];
 const render=()=>renderer.render(scene,camera);controls.addEventListener('change',render);const resize=()=>{const {width,height}=el.getBoundingClientRect();renderer.setSize(width,height);camera.aspect=width/Math.max(1,height);camera.position.copy(new T.Vector3(.48,.22,.85).normalize().multiplyScalar(Math.max(78,43/camera.aspect)).add(controls.target));camera.updateProjectionMatrix();controls.update();render()};const ro=new ResizeObserver(resize);ro.observe(el);state.current={texture,scene,meshes,render,controls};resize();
 let down=false;const pick=(e:PointerEvent)=>{if(!state.current||state.current.controls.enabled)return;const rect=renderer.domElement.getBoundingClientRect();const ray=new T.Raycaster();ray.setFromCamera(new T.Vector2((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1),camera);const hit=ray.intersectObjects(meshes).find(h=>h.object.visible&&h.object.userData.layer===el.dataset.layer);if(hit?.uv)callback.current?.(Math.min(63,Math.max(0,Math.floor(hit.uv.x*64))),Math.min(63,Math.max(0,Math.floor((1-hit.uv.y)*64))));};const start=(e:PointerEvent)=>{down=true;renderer.domElement.setPointerCapture(e.pointerId);pick(e)};const move=(e:PointerEvent)=>{if(down)pick(e)};const end=()=>{down=false};renderer.domElement.addEventListener('pointerdown',start);renderer.domElement.addEventListener('pointermove',move);renderer.domElement.addEventListener('pointerup',end);renderer.domElement.addEventListener('pointercancel',end);
 return()=>{ro.disconnect();controls.dispose();texture.dispose();meshes.forEach(m=>{m.geometry.dispose();(m.material as T.Material).dispose()});renderer.dispose();el.replaceChildren();state.current=null};
 },[]);
 useEffect(()=>{const s=state.current;if(!s)return;s.controls.enabled=!paint;},[paint]);
 useEffect(()=>{const s=state.current;if(!s)return;s.texture.image=pixelCanvas(skin.pixels);s.texture.needsUpdate=true;for(const m of s.meshes){s.scene.remove(m.parent!);m.geometry.dispose();(m.material as T.Material).dispose()}s.meshes.length=0;
 const regs=atlas(skin.model);for(const part of parts){const [w,h,d]=dimensions(part,skin.model);const pivot=new T.Group();const isArm=part.includes('arm'),isLeg=part.includes('leg'),left=part.startsWith('left');pivot.position.set(part==='head'||part==='body'?0:(left?1:-1)*(isArm?4+w/2:2),part==='head'?24:part==='body'?24:isArm?24:12,0);
 if(view.pose==='walk'){if(isArm)pivot.rotation.x=left?-.65:.65;if(isLeg)pivot.rotation.x=left?.65:-.65}if(view.pose==='tpose'&&isArm)pivot.rotation.z=left?Math.PI/2:-Math.PI/2;if(view.pose==='wave'&&part==='right_arm'){pivot.rotation.z=-2.5;pivot.rotation.x=-.2}if(view.pose==='sit'&&isLeg)pivot.rotation.x=-Math.PI/2;
 for(const layer of ['base','overlay'] as const){const expand=layer==='overlay'?(part==='head'?.5:.25):0;const g=new T.BoxGeometry(w+expand*2,h+expand*2,d+expand*2);const uv=g.attributes.uv;const order=['left','right','top','bottom','front','back'];order.forEach((face,f)=>{const r=regs.find(r=>r.part===part&&r.layer===layer&&r.face===face)!;const a=[[r.x,r.y],[r.x+r.width,r.y],[r.x,r.y+r.height],[r.x+r.width,r.y+r.height]];a.forEach(([x,y],j)=>uv.setXY(f*4+j,x/64,1-y/64));});const mat=new T.MeshLambertMaterial({map:s.texture,transparent:layer==='overlay',alphaTest:layer==='base'?0:.01,side:T.FrontSide});const mesh=new T.Mesh(g,mat);mesh.position.y=part==='head'?h/2:-h/2;mesh.visible=view.visible[part]&&(layer==='base'?view.showBase:view.showOverlay);mesh.userData={part,layer};pivot.add(mesh);s.meshes.push(mesh)}s.scene.add(pivot)}s.render();
 },[skin,view]);
 return <div ref={host} className="skin-view" data-layer={view.layer} aria-label={`3D skin preview, ${view.pose} pose`}/>;
}
